modLoader = "javafml"
loaderVersion = "*"
license = "ARR"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "CopicraftDev"
description = "This is an example Mod made by copicraft! I will use this as a template to my mods."
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "template-common.mixins.json"

[[mixins]]
config = "template-forge.mixins.json"